# Generated by Django 2.0.7 on 2018-07-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180721_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('is_library_member', 'A Library Member'),)},
        ),
    ]
