# Generated by Django 2.0.7 on 2018-07-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180721_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('is_library_member', 'A Library Member'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('is_library_member', 'A Library Member'),)},
        ),
    ]
